

CXX = g++
CXXFLAGS = -std=c++11


OBJECTS = main.o direction.o engine.o field.o food.o point.o snake.o


TARGET = game


LIBS = -ldirection -lengine -lfield -lfood -lpoint -lsnake


all: $(TARGET)

$(TARGET): $(OBJECTS) libdirection.a libengine.a libfield.a libfood.a libpoint.a libsnake.a
    $(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)

%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c $< -o $@

clean:
    rm -f $(OBJECTS) $(TARGET)
